name: Deploy Laravel to InfinityFree

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" # Adjust to your PHP version
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Create .htaccess file
        run: |
          echo "RewriteEngine On" > .htaccess
          echo "RewriteBase /" >> .htaccess
          echo "RewriteCond %{THE_REQUEST} /public/([^\s?]*) [NC]" >> .htaccess
          echo "RewriteRule ^ %1 [L,NE,R=302]" >> .htaccess
          echo "RewriteRule ^((?!public/).*)$ public/$1 [L,NC]" >> .htaccess
      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-interaction

      - name: Create .env file
        run: echo "${{secrets.ENV}}" > .env

      - name: Upload to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Adjust if necessary
          server-dir: /htdocs/ # Adjust to your server's document root
          exclude: |
            .env 
            storage/*
